sudo: required

language: python

services:
  - docker

before_install:
  - docker build .

script:
  - docker-compose run web python Backend/doc_ta/manage.py migrate
  - docker-compose run web python Backend/doc_ta/manage.py test
